const productos = [
    {
        id: 13,
        img: "images/carta/pomodorini.jpg",
        titulo: "Pomodorini, Bocconcini & Pesto",
        description: "Tomates cherry, bocconcini, salame y pesto de la casa.",
        price: 35,
    },
    {
        id: 14,
        img: "images/carta/burrata.jpg",
        titulo: "Burrata",
        description: "Queso en forma de bolsa relleno de Stracciatella con aceite de oliva, sal, pimienta y albahaca.",
        price: 35,
    },
    {
        id: 15,
        img: "images/carta/prosciutto.jpg",
        titulo: "Prosciutto & Mozzarella",
        description: "Jamón curado acompañado de salame, bocconcini y queso Parmigiano Reggiano DOP",
        price: 39,
    },
    {
        id: 16,
        img: "images/carta/marinara.jpg",
        titulo: "Pizza Marinara",
        description: "Salsa de tomates San Marzano DOP, orégano, ajo, aceite de oliva extra virgen.",
        price: 45,
    },
    {
        id: 17,
        img: "images/carta/margarina.jpg",
        titulo: "Pizza Margarita",
        description: "Salsa de tomates San Marzano DOP, mozzarella fior di latte, albahaca, aceite de oliva extra virgen.",
        price: 50,
    },
    {
        id: 18,
        img: "images/carta/salame.jpg",
        titulo: "Pizza Salame",
        description: "Salsa de tomates San Marzano DOP, mozzarella fior di latte, salame.",
        price: 55,
    },
    {
        id: 19,
        img: "images/carta/vinoterre.jpg",
        titulo: "Vino Terre Forti | Tinto | Botella",
        description: "Merlot, Faenza, Ravena.",
        price: 100,
    },
    {
        id: 20,
        img: "images/carta/vinoterre.jpg",
        titulo: "Vino Terre Forti | Tinto | Copa",
        description: "Merlot, Faenza, Ravena.",
        price: 23,
    },
    {
        id: 21,
        img: "images/carta/vinopiccini.jpg",
        titulo: "Vino Piccini Bianco IGT | Blanco | Botella",
        description: "Trebbiano, Vermentino, Chardonnay, Castillina in Chianti, Toscana.",
        price: 125,
    },
    {
        id: 22,
        img: "images/carta/vinopiccini.jpg",
        titulo: "Vino Piccini Bianco IGT | Blanco | Copa",
        description: "Trebbiano, Vermentino, Chardonnay, Castillina in Chianti, Toscana.",
        price: 28,
    },
    {
        id: 23,
        img: "images/carta/vinobottega.jpg",
        titulo: "Vino Bottega Pinot Grigio Venezia DOC | Blanco | Botella",
        description: "Pinot Grigio 100%, Treviso, Veneto.",
        price: 175,
    },
    {
        id: 24,
        img: "images/carta/fugazzeta.jpg",
        titulo: "Pizza Fugazzeta",
        description: "Extra mozzarella, cebolla blanca, pimienta, oregano, aceite de oliva extra virgen",
        price: 55,
    },
    {
        id: 25,
        img: "images/carta/capricciosa.jpg",
        titulo: "Pizza Capricciosa",
        description: "Salsa de tomates San Marzano DOP, mozzarella fior di latte, jamon de pierna, champiñones",
        price: 59,
    },
    {
        id: 26,
        img: "images/carta/anchoas.jpg",
        titulo: "Pizza Con anchoas",
        description: "Salsa de tomate, mozzarella fior di latte, anchoas, albahaca, aceite de oliva extra virgen",
        price: 55,
    },
    {
        id: 27,
        img: "images/carta/salsiccia.jpg",
        titulo: "Pizza Salsiccia Italiana y Pesto Picante",
        description: "Mozzarella flior di latte, sasiccia italiana, tomates cherry, pesto picante, pimienta",
        price: 59,
    },
    {
        id: 28,
        img: "images/carta/olive.jpg",
        titulo: "Pizza olive y pomodorini",
        description: "Salsa de tomates, mozzarella, aceitunas negras, tomates cherry, queso parmigiano, albahaca, aceite de oliva extra virgen",
        price: 55,
    },
    {
        id: 29,
        img: "images/carta/pizza-prosciutto.jpg",
        titulo: "Pizza Prosciutto y arugula",
        description: "Salsa de tomate, mozzrella, jamon curado, arugula, queso parmigiano, aceite de oliva extra virgen",
        price: 59,
    },
    {
        id: 30,
        img: "images/carta/polpette.jpg",
        titulo: "Pizza Polpette y Stracciatella",
        description: "Salsa de tomate, mozzrella, polpette, stracciatella, albahaca, aceite de oliva extra virgen",
        price: 59,
    },
    {
        id: 31,
        img: "images/carta/calzone.jpg",
        titulo: "Pizza Calzone Napoletano",
        description: "Relleno de ricotta, mozzarella, salame picante, pimienta",
        price: 59,
    },
    {
        id: 32,
        img: "images/carta/caprese.jpg",
        titulo: "Caprese",
        description: "Mozzarella, tomates cherry, pesto, aceite de oliva extra virgen",
        price: 39,
    },
    {
        id: 33,
        img: "images/carta/ss.jpg",
        titulo: "Salame y Stracciatella",
        description: "Salame stracciatella, pimienta, aceite de oliva extra virgen",
        price: 45,
    },
    {
        id: 34,
        img: "images/carta/pa.jpg",
        titulo: "Prosciutto y Arugula",
        description: "Mozzarella, arugula, prosciutto, aceite de oliva extra virgen",
        price: 59,
    },
    {
        id: 35,
        img: "images/carta/pesto.jpg",
        titulo: "Pesto",
        description: "Tradicional salsa a base de albahaca, aceite de oliva, queso Parmigiano reggiano DOP y ajo",
        price: 45,
    },
    {
        id: 36,
        img: "images/carta/rb.jpg",
        titulo: "Ragú alla bolognese",
        description: "Tradicional salsa a base de carne molida y tomates italianos",
        price: 47,
    }
];
