const promosItems = [
    {
        id: 1,
        cat: "pasta",
        img: "images/cacioepepe.jpg",
        titulo: "MIÉRCOLES NOCTURNO DE PASTA",
        description: "Disfruta de nuestra Pasta Cacio e Pepe y una copa de vino de la casa",
        price: 60,
    },
    {
        id: 2,
        cat: "pasta",
        img: "images/albondigascarne.jpg",
        titulo: "GIRO ITALIANO",
        description: "Spaghetti con Albóndigas de Carne",
        price: 30,
    },
    {
        id: 3,
        cat: "pasta",
        img: "images/fetuccinipesto.jpg",
        titulo: "COMBO PASTA Y POSTRE",
        description: "Fettuccine Pesto y de postre un Tiramisú",
        price: 40,
    }, {
        id: 4,
        cat: "vinos",
        img: "images/raicesnegras.jpg",
        titulo: "DOBLE PLACER",
        description: "¡2 botella de Raices Negras y Blanco!",
        price: 63,
    },
    {
        id: 5,
        cat: "vinos",
        img: "images/vinoconde.jpg",
        titulo: "SABOR BOLOGNESE COMPLETO",
        description: "Recibe una copa de vino gratis por la compra de una Lasagna Alla Bolognese",
        price: 35,
    },
    {
        id: 6,
        cat: "vinos",
        img: "images/catavinos.jpg",
        titulo: "SÁBADO DE CATAR VINOS",
        description: "¡Participa en nuestra cata de vinos por una seleccion de tres vinos diferentes, Cabernet Sauvignon, Chardonnay  y Malbec Gran Reserva!",
        price: 150,
    }, {
        id: 7,
        cat: "pizza",
        img: "images/pizzamarinara.jpg",
        titulo: "MARTES Y JUEVES ESPECIAL",
        description: "¡2x1! 2 Pizzas Marinaras a solo un precio",
        price: 60,
    },
    {
        id: 8,
        cat: "pizza",
        img: "images/pizzasalame.jpg",
        titulo: "¡COMBO FAMILIAR!",
        description: "Compra una Pizza Salame y recibe una Pizza Margarita gratis.",
        price: 75,
    },
    {
        id: 9,
        cat: "pizza",
        img: "images/duoperfecto.jpg",
        titulo: "DUO PERFECTO",
        description: "Disfruta de una Pizza Calzone Napoletano junto con una Gaseosa personal.",
        price: 58,
    }, {
        id: 10,
        cat: "bebida",
        img: "images/coctelbienvenida.jpg",
        titulo: "¡CÓCTEL DE REGALO!",
        description: "Recibe un cóctel de bienvenida gratuito al ordenar una Ravioli al Pomodoro.",
        price: 55,
    },
    {
        id: 11,
        cat: "bebida",
        img: "images/tehelado.jpg",
        titulo: "LUNES Y VIERNES DE HAPPY HOUR",
        description: "Difruta de 3 de nuestras Cervezas Artesanales de 5pm a 7pm",
        price: 40,
    },
    {
        id: 12,
        cat: "bebida",
        img: "images/copalimoncello.jpg",
        titulo: "¡LIMONCELLO TE ESPERA!",
        description: "Prueba nuestra licor de limones de Sorrento (Cóctel) gratis por la compra de una Pizza Margarita",
        price: 70,
    }
];
